#!/usr/bin/env bash
#Installs a nginx web server on my server 454715-web-01

#Updating packages pre-installations
sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install nginx

#Configuring uncomplicated firewall to allow incoming traffic.

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#Testing Nginx configurations for syntax errors
sudo nginx -t

#Restarting Nginx web server
sudo service nginx start
