#!/usr/bin/env bash
#Configures my nginx web server to perform a 301 Moved permanently redirection

#Updating packages pre-installations
sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install nginx

#Configuring uncomplicated firewall to allow incoming traffic.

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Tanagends permanent;"
sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

#Testing Nginx configurations for syntax errors
sudo nginx -t

#Restarting Nginx web server
sudo service nginx start
