#!/usr/bin/bash
#Installs a firewall. blocks all incoming traffic
#Except the following tcp ports: 22, 443, 80.

sudo apt update
sudo apt install ufw

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
sudo ufw status
